cms/urls.py
from django.urls import path
from cms import views


app_name = 'cms'
urlpatterns = [
    # 書籍
    #path('book/', views.book_list, name='book_list'),   # 一覧
    path('book/', views.IndexView.as_view(), name='book_list'),
    path('book/add/', views.book_edit, name='book_add'),  # 登録
    path('book/mod/<int:book_id>/', views.book_edit, name='book_mod'),  # 修正
    path('book/del/<int:book_id>/', views.book_del, name='book_del'),   # 削除
    path('jpro/', views.JproView.as_view(), name='jpro_list'),
]

selectbooks3/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('cms/', include('cms.urls')),
    path('admin/', admin.site.urls),
]

cms/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    """書籍"""
    ISBN = models.CharField('ISBN', max_length=255, blank=True)
    ASIN = models.CharField('ASIN', max_length=255, blank=True)
    NDLBibID = models.CharField('NDL書誌ID', max_length=255)
    title = models.CharField('書名', max_length=255)
    volume = models.CharField('巻次', max_length=255, blank=True)
    seriesTitle = models.CharField('シリーズ名', max_length=255)
    creator = models.CharField('著者名', max_length=255, blank=True)
    publisher = models.CharField('出版者', max_length=255)
    publicationPlace = models.CharField('出版地', max_length=255, blank=True)
    date = models.CharField('出版年', max_length=255)
    NDC = models.CharField('NDC', max_length=255, blank=True)
    subject = models.CharField('件名', max_length=255, blank=True)
    price = models.CharField('価格', max_length=255, blank=True)
    extent = models.CharField('ページ数', max_length=255, blank=True)
    description = models.CharField('注記', max_length=255, blank=True)
    partTC = models.CharField('内容', max_length=255, blank=True)
    #photo = 'https://iss.ndl.go.jp/thumbnail/' + ISBN.replace('-', '')

class jpro(models.Model):
    ISBN = models.CharField('ISBN', max_length=255, blank=True)
    title = models.CharField('書名', max_length=255)
    volume = models.CharField('巻次', max_length=255, blank=True)
    subtitle = models.CharField('副書名', max_length=255, blank=True)
    series = models.CharField('シリーズ名', max_length=255, blank=True)
    creator = models.CharField('著者名', max_length=255, blank=True)
    publisher = models.CharField('出版者', max_length=255)
    date = models.CharField('出版日', max_length=255)
    price = models.CharField('価格', max_length=255, blank=True)
    extent = models.CharField('ページ数', max_length=255, blank=True)
    ccode = models.CharField('Cコード', max_length=255, blank=True)
    genrecode = models.CharField('ジャンルコード', max_length=255, blank=True)
    keywords = models.CharField('キーワード', max_length=255, blank=True)
    audience = models.CharField('対象年齢', max_length=255, blank=True)
    creatornote = models.CharField('著者紹介', max_length=255, blank=True)
    description = models.CharField('内容', max_length=1000, blank=True)
    ToC = models.CharField('目次', max_length=1000, blank=True)
    datemodified = models.CharField('データ修正日', max_length=255, blank=True)
    NDC = models.CharField('NDC', max_length=255, blank=True)

    def __str__(self):
        return self.title

cms/views.py
from django.shortcuts import render
from django.http import HttpResponse
from cms.models import Book, jpro
from django.views import generic


class IndexView(generic.ListView):
    model = Book
    template_name = 'cms/book_list.html'
    context_object_name = 'books'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        books = Book.objects.all().order_by('id')
        self.object_list = books

        context = self.get_context_data(object_list=self.object_list)
        return self.render_to_response(context)

class JproView(generic.ListView):
    model = jpro
    template_name = 'cms/jpro_list.html'
    context_object_name = 'jpro_books'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        jpro_books = jpro.objects.all().order_by('NDC')
        self.object_list = jpro_books

        context = self.get_context_data(object_list=self.object_list)
        return self.render_to_response(context)

def book_edit(request, book_id=None):
    """書籍の編集"""
    return HttpResponse('書籍の編集')

def book_del(request, book_id):
    """書籍の削除"""
    return HttpResponse('書籍の削除')

cms/templates/cms/base.html
{% load i18n static %}
{% load customfilter %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'cms/css/bootstrap.min.css' %}">
  <!-- Bootstrap4 -->
        {% load bootstrap4 %}
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
        <!-- Bootstrap4 -->
{% block extra_css %}{% endblock %}
<title>{% block title %}My books{% endblock %}</title>
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
<script src="{% static 'cms/js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'cms/js/bootstrap.bundle.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

cms/templates/cms/book_list.html
{% extends "cms/base.html" %}
{% load customfilter %}
{% block title %}NDL作成中書誌{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">NDL作成中書誌</h4>
    <a href="{% url 'cms:book_add' %}" class="btn btn-primary btn-sm my-3">追加</a>

    {% include "cms/pagination.html" %}

    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">表紙</th>
          <th scope="col">書誌事項</th>
          <th scope="col">分類件名</th>
          <!-- <th scope="col">操作</th> -->
        </tr>
      </thead>
      <tbody>
        {% for book in books %}
        <tr>
          <th scope="row">{{ book.id }}</th>
          <td><img src="https://iss.ndl.go.jp/thumbnail/{{ book.ISBN|cut:"-" }}" width="112" height="160"
            onerror="this.onerror=null;this.src='http://images-jp.amazon.com/images/P/{{ book.ASIN }}.09.MZZZZZZZ.jpg';"/></td>
          <td><b>{{ book.title }} {{ book.volume }}
            {% if book.seriesTitle %}
              ({{ book.seriesTitle }})
            {% endif %}</b><br>
            {{ book.creator }}. {{ book.publisher }}, {{ book.publicationPlace }}, {{ book.extent}},
            {{ book.date }} {{ book.price}}<br>
            {% if book.description %}
              {{ book.description }}<br>
            {% endif %}
            {{ book.ISBN }}
            {% if book.partTC %}
            <br><b>[内容]</b><br>
              {{ book.partTC|lineRep|linebreaksbr }}
            {% endif %}</td>
          <td><b>{{ book.NDC }}</b><br>
          {{ book.subject|lineRep|linebreaksbr }}</td>
          <!-- <td>
            <a href="{% url 'cms:book_mod' book_id=book.id %}" class="btn btn-outline-primary btn-sm">修正</a>
            <a href="{% url 'cms:book_del' book_id=book.id %}" class="btn btn-outline-danger btn-sm">削除</a>
          </td> -->
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% include "cms/pagination.html" %}

{% endblock content %}

cms/templates/cms/jpro_list.html
{% extends "cms/base.html" %}
{% load customfilter %}
{% block title %}JPRO本日発売書誌{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">JPRO本日発売書誌</h4>

    {% include "cms/pagination.html" %}

    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <!-- <th scope="col">ID</th> -->
          <th scope="col">表紙</th>
          <th scope="col">書誌事項</th>
          <th scope="col">分類件名</th>
          <!-- <th scope="col">操作</th> -->
        </tr>
      </thead>
      <tbody>
        {% for jpro in jpro_books %}
        <tr>
          <!-- <th scope="row">{{ jpro.id }}</th> -->
          <td><img src="https://iss.ndl.go.jp/thumbnail/{{ jpro.ISBN|cut:"-" }}" width="112" height="160"
            onerror="this.onerror=null;this.src='http://images-jp.amazon.com/images/P/{{ jpro.ASIN }}.09.MZZZZZZZ.jpg';"/></td>
          <td><b>{{ jpro.title }} {{ jpro.volume }}
            {% if jpro.series %}
              ({{ jpro.series }})
            {% endif %}</b><br>
            {{ jpro.creator }}. {{ jpro.publisher }}, {{ jpro.extent}}
              {% if jpro.price %}
                {{ jpro.price}}円
              {% endif %}
              {{ jpro.date }}
              <br>
            {{ jpro.ISBN }}
            {% if jpro.description %}
              {% if jpro.description|length < 200 %}
              <br><b>[内容紹介]</b>
                <br>{{ jpro.description }}<br>
              {% else %}
                <details><summary><b>[内容紹介]</b>
                  <br>{{ jpro.description|slice:":100" }}……</summary>
              {{ jpro.description|slice:"100:" }}</details>
              {% endif %}
            {% endif %}
            {% if jpro.creatornote %}
            {% if jpro.creatornote|length < 200 %}
            <b>[著者紹介]</b>
              <br>{{ jpro.creatornote }}<br>
            {% else %}
                <details><summary><b>[著者紹介]</b>
                  <br>{{ jpro.creatornote|slice:":100" }}……</summary>
              {{ jpro.creatornote|slice:"100:" }}</details>
              {% endif %}
            {% endif %}
            {% if jpro.keywords %}
            <b>[キーワード]</b>
          {{ jpro.keywords|lineSpace }}
          {% endif %}
          {% if jpro.ToC %}
            {% if jpro.ToC|length < 100 %}
              <br><b>[目次]</b><br>
              {{ jpro.ToC|lineRep|linebreaksbr }}
            {% else %}
              <details><summary><b>[目次]</b></summary>
                {{ jpro.ToC|lineRep|linebreaksbr }}</details>
            {% endif %}
            {% endif %}</td>
          <td><b>NDC : {{ jpro.NDC }}</b><br>
            {% if jpro.ccode %}
              Cコード {{ jpro.ccode }}<br>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% include "cms/pagination.html" %}

{% endblock content %}

cms/templates/cms/pagination.html
<nav aria-label="Page navigation">
<ul class="pagination">
  {% if page_obj.has_previous %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
      <span aria-hidden="true">&lt;</span>
    </a>
  </li>
  {% endif %}

  {% if page_obj.number > 3 %}
  <li class="page-item">
    <a class="page-link" href="?page=1" aria-label="First">1</a>
  </li>
  {% endif %}

  {% if page_obj.number > 4 %}
  <li class="page-item"><span class="page-link" aria-hidden="true">...</span></li>
  {% endif %}

  {% for link_page in page_obj.paginator.page_range %}
  {% if link_page == page_obj.number %}
  <li class="page-item active">
    <a class="page-link" href="?page={{ link_page }}">
      {{ link_page }}
    </a>
  </li>
  {% elif link_page < page_obj.number|add:3 and link_page > page_obj.number|add:-3 %}
  <li class="page-item">
    <a class="page-link" href="?page={{ link_page }}">
      {{ link_page }}
    </a>
  </li>
  {% endif %}
  {% endfor %}

  {% if page_obj.number < page_obj.paginator.num_pages|add:-3 %}
  <li class="page-item"><span class="page-link" aria-hidden="true">...</span></li>
  {% endif %}

  {% if page_obj.number < page_obj.paginator.num_pages|add:-2 %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">{{ page_obj.paginator.num_pages}}</a>
  </li>
  {% endif%}

  {% if page_obj.has_next %}
  <li class="page-item">
    <a class="page-link" href="?page={{page_obj.next_page_number }}" aria-label="Next">
      <span aria-hidden="true">&gt;</span>
    </a>
  </li>
  {% endif %}
</ul>
</nav>